import Head from 'next/head'
import NavBar from '../../components/NavBar'
const battle3 = () => {
  return (
    <>
      <Head>
        <title>Css Battles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <div>
        <h1>Battle 3</h1>
      </div>
    </>
  )
}
export default battle3
