import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Css Battles</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar />
      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to my CSS Battles!
          </h1>

          <div className={styles.grid}>
            <Link href='/battle1'>
              <a className={styles.card}>
                <h2>Battle 1</h2>
                <p>First ever battle of CSSBattle.</p>
              </a>
            </Link>

            <Link href='/battle2'>
              <a className={styles.card}>
                <h2>Battle 2</h2>
                <p>6 targets unlock across 3 weeks.</p>
              </a>
            </Link>
            <Link href='/battle3'>
              <a className={styles.card}>
                <h2>Battle 3</h2>
                <p>
                  First ever mini-battle. 48 hours, 2
                  Targets. Some intense CSS golfing.
                </p>
              </a>
            </Link>
            <Link href='/battle4'>
              <a className={styles.card}>
                <h2>Battle 4</h2>
                <p>8 targets unlock across 3 weeks.</p>
              </a>
            </Link>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            target='_blank'
            rel='noopener noreferrer'>
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src='/vercel.svg'
                alt='Vercel Logo'
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  )
}
