import Head from 'next/head'
import NavBar from '../../components/NavBar'
const battle4 = () => {
  return (
    <>
      <Head>
        <title>Css Battles - Battle 4</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <div>
        <h1>Battle 4</h1>
      </div>
    </>
  )
}
export default battle4
